trigger:
  branches:
    include: [ '*' ]
    exclude: [ 'refs/tags/*' ]

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- powershell: .\build.ps1 --target=CI --configuration=$(BuildConfiguration)
  displayName: Build, package, and test

- task: PublishBuildArtifacts@1
  displayName: Publish bin artifacts
  inputs:
    PathtoPublish: $(build.sourcesdirectory)\bin\$(BuildConfiguration)
    ArtifactName: Bin
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: Publish package artifacts
  inputs:
    PathtoPublish: $(build.sourcesdirectory)\package
    ArtifactName: Package
  condition: succeededOrFailed()
